### ISSUE TITLE
CI fails during "test"

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/solda-aliens4friends-dashboard#32]
See https://github.com/noi-techpark/aliens4friends-dashboard/pull/31 for details

**Comment by Piiit** [comment]
@ag0n-e I gave you now also access to your Kanban used by Martin mostly for documentation, but I think we can extend it to all activities where he is involved.... ok, @mrabans ?

https://github.com/orgs/noi-techpark/projects/15

**Comment by mrabans** [comment]
@Piiit there has been no changes in the configuration files so far. We've worked on your latest development branch which didn't fail previously. It seems to be a problem with the environment in the pipeline.

Not sure if this could be the reason but the workspace is called *ingmachine* instead of *testingmachine* 
`--entrypoint= -w /var/lib/jenkins/workspace/ingmachine.solda.dashboard_PR-31`

The weird thing about is that the [deployment #16](https://ci.opendatahub.bz.it/job/eu.testingmachine.solda.dashboard/job/development/16/console) didn't fail but here as well the workspace was named *hine* instead of *testingmachine*
`docker run -t -d -u 109:113 --entrypoint= -w /var/lib/jenkins/workspace/hine.solda.dashboard_development -v `
